name: 'Setup'
description: 'Setup tooling via asdf from .tool-versions'
runs:
  using: "composite"
  steps:
    - name: Install asdf
      uses: asdf-vm/actions/setup@v3

    - name: Install Dojo asdf plugins
      run: curl -L https://install.dojoengine.org | bash
      shell: bash

    - name: Install scarb plugin
      run: asdf plugin add scarb || true
      shell: bash

    - name: Install tool versions from .tool-versions
      run: asdf install
      shell: bash