[package]
name = "game_erc721"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin_token.workspace = true
openzeppelin_access.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_security.workspace = true
openzeppelin_upgrades.workspace = true
openzeppelin_interfaces.workspace = true

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
