// États possibles de la machine
export enum GameState {
  WAITING,
  DRAGGING,
  GRAVITY,
  GRAVITY2,
  GRAVITY_BONUS,
  LINE_CLEAR,
  LINE_CLEAR2,
  LINE_CLEAR_BONUS,
  ADD_LINE,
  UPDATE_AFTER_MOVE,
  UPDATE_AFTER_BONUS,
}
