[world]
name = "zKube"
description = "Reversed tetris fully onchain."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://app.zkube.xyz"
seed = "zKube"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "zkube2"

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x63a7373ece40e853d9cca9c5889527cab3b7aab669e390e2245225718794b58"
private_key = "0x2c8edd6c146cf85ad3dba64865728a79113171782afddd5054d9e9f4c93857f"

[init_call_args]
"zkube2-chest" = ["0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"]
"zkube2-settings" = ["0x0", "0x0"]
"zkube2-tournament" = ["0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"]
"zkube2-zkorp" = ["0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7"]

[writers]
"zkube2-Admin" = ["zkube2-settings"]
"zkube2-Chest" = ["zkube2-chest", "zkube2-play"]
"zkube2-Game" = ["zkube2-play"]
"zkube2-Mint" = ["zkube2-minter"]
"zkube2-Participation" = ["zkube2-chest", "zkube2-play"]
"zkube2-Player" = ["zkube2-account", "zkube2-play"]
"zkube2-Settings" = ["zkube2-minter", "zkube2-settings"]
"zkube2-Tournament" = ["zkube2-play", "zkube2-tournament"]
"zkube2-TrophyCreation" = ["zkube2-settings"]
"zkube2-TrophyProgression" = ["zkube2-play"]