[world]
name = "zKube"
description = "Reversed tetris fully onchain."
website = "https://app.zkube.xyz"
seed = "zkube_v2"

[world.socials]
x = "https://x.com/zKube_game"
discord = "https://discord.gg/pzzRSDZY"
github = "https://github.com/z-korp/zkube"
telegram = "https://t.me/dojoengine"

[namespace]
default = "zkube_v2_1_0"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet/rpc/v0_8"
account_address = "0x0601ecb93c6e88eec432910a2c3ab4d9b5c0dd768b55ab4f8c89336e01fafaa7"

[writers]
"zkube_v2_1_0" = [
    "zkube_v2_1_0-game_system",
    "zkube_v2_1_0-move_system",
    "zkube_v2_1_0-grid_system",
    "zkube_v2_1_0-level_system",
    "zkube_v2_1_0-config_system",
    "zkube_v2_1_0-daily_challenge_system",
    "zkube_v2_1_0-renderer_systems",
]

[init_call_args]
"zkube_v2_1_0-game_system" = [
    "0x0601ecb93c6e88eec432910a2c3ab4d9b5c0dd768b55ab4f8c89336e01fafaa7", # creator
    "0x036017E69D21D6D8c13E266EaBB73ef1f1D02722D86BDcAbe5f168f8e549d3cD", # Denshokan
    "0x0", "0x0", # renderer_address: Option::None
    "0x0",        # vrf_address (configure post-deploy)
]
"zkube_v2_1_0-config_system" = [
    "0x0601ecb93c6e88eec432910a2c3ab4d9b5c0dd768b55ab4f8c89336e01fafaa7", # creator
    "0x0", # cube_token_address
]
"zkube_v2_1_0-daily_challenge_system" = [
    "0x0601ecb93c6e88eec432910a2c3ab4d9b5c0dd768b55ab4f8c89336e01fafaa7", # admin
    "0x0", # lords_address
]

[migration]
order_inits = [
    "zkube_v2_1_0-game_system",
    "zkube_v2_1_0-config_system",
    "zkube_v2_1_0-daily_challenge_system",
]
