[world]
name = "zKube"
description = "Reversed tetris fully onchain."
# cover_uri = "file://assets/cover.png"
# icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "zKube1"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/dojo-starter"
telegram = "https://t.me/dojoengine"

[namespace]
default = "zkube4"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x0601ecb93c6e88eec432910a2c3ab4d9b5c0dd768b55ab4f8c89336e01fafaa7"

[init_call_args]
"zkube4-chest" = ["0x021d1aa0b2c3413f0b8a1c14ddcdbaf404debfb0d4d858d0bb6ccb48ec1c0c51"]
"zkube4-settings" = ["0x0589d37adc1e5cf9ef58da510ee904aa9428d6e9a1c0d5c822392664d063796b", "0x0589d37adc1e5cf9ef58da510ee904aa9428d6e9a1c0d5c822392664d063796b"]
"zkube4-tournament" = ["0x021d1aa0b2c3413f0b8a1c14ddcdbaf404debfb0d4d858d0bb6ccb48ec1c0c51"]
"zkube4-zkorp" = ["0x021d1aa0b2c3413f0b8a1c14ddcdbaf404debfb0d4d858d0bb6ccb48ec1c0c51"]

[writers]
"zkube4-Admin" = ["zkube4-settings"]
"zkube4-Chest" = ["zkube4-chest", "zkube4-play"]
"zkube4-Game" = ["zkube4-play"]
"zkube4-GamePrize" = ["zkube4-play"]
"zkube4-Mint" = ["zkube4-minter"]
"zkube4-Participation" = ["zkube4-chest", "zkube4-play"]
"zkube4-Player" = ["zkube4-account", "zkube4-play"]
"zkube4-PlayerInfo" = ["zkube4-account", "zkube4-play"]
"zkube4-Settings" = ["zkube4-minter", "zkube4-settings"]
"zkube4-Tournament" = ["zkube4-play", "zkube4-tournament"]
"zkube4-TournamentPrize" = ["zkube4-play", "zkube4-tournament"]
"zkube4-TrophyCreation" = ["zkube4-settings"]
"zkube4-TrophyProgression" = ["zkube4-play"]
"zkube4-TestModel" = ["zkube4-test"]