[package]
name = "zkube"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true

[cairo]
sierra-replace-ids = true

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[scripts]
slot = "sozo --profile slot clean && sozo --profile slot build && sozo --profile slot migrate --guest"
sepolia = "sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia migrate --guest --keystore /Users/matthias/.starkli-wallets/sepolia/braavos_dojo_deployer/keystore.json"
mainnet = "sozo --profile mainnet clean && sozo --profile mainnet build && sozo --profile mainnet migrate --guest --keystore /Users/matthias/.starkli-wallets/mainnet/braavos_dojo_deployer/keystore.json"

inspect-sepolia = "sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia inspect"
inspect-mainnet = "sozo --profile mainnet clean && sozo --profile mainnet build && sozo --profile mainnet inspect"

[dependencies]
dojo.workspace = true
starknet.workspace = true
openzeppelin_token.workspace = true
openzeppelin_introspection.workspace = true
openzeppelin_access.workspace = true
alexandria_math.workspace = true
alexandria_encoding.workspace = true
origami_random.workspace = true
game_components_embeddable_game_standard.workspace = true
graffiti.workspace = true
quest.workspace = true
achievement.workspace = true

[[target.starknet-contract]]
casm = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    # Quest models
    "quest::models::index::m_QuestDefinition",
    "quest::models::index::m_QuestCompletion",
    "quest::models::index::m_QuestAdvancement",
    "quest::models::index::m_QuestAssociation",
    "quest::models::index::m_QuestCondition",
    # Quest events
    "quest::events::index::e_QuestCreation",
    "quest::events::index::e_QuestProgression",
    "quest::events::index::e_QuestUnlocked",
    "quest::events::index::e_QuestCompleted",
    "quest::events::index::e_QuestClaimed",
    # Achievement models
    "achievement::models::index::m_AchievementDefinition",
    "achievement::models::index::m_AchievementCompletion",
    "achievement::models::index::m_AchievementAdvancement",
    "achievement::models::index::m_AchievementAssociation",
    # Achievement events
    "achievement::events::index::e_TrophyCreation",
    "achievement::events::index::e_TrophyProgression",
    "achievement::events::index::e_AchievementCompleted",
    "achievement::events::index::e_AchievementClaimed",
]

[dev-dependencies]
dojo_cairo_test.workspace = true
cairo_test.workspace = true
