[package]
name = "zkube"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true

[cairo]
sierra-replace-ids = true

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[scripts]
slot = "sozo --profile slot clean && sozo --profile slot build && sozo --profile slot migrate --guest"
sepolia = "sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia migrate --guest --keystore /Users/matthias/.starkli-wallets/sepolia/braavos_dojo_deployer/keystore.json"
mainnet = "sozo --profile mainnet clean && sozo --profile mainnet build && sozo --profile mainnet migrate --guest --keystore /Users/matthias/.starkli-wallets/mainnet/braavos_dojo_deployer/keystore.json"

inspect-sepolia = "sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia inspect"
inspect-mainnet = "sozo --profile mainnet clean && sozo --profile mainnet build && sozo --profile mainnet inspect"

[dependencies]
dojo.workspace = true
starknet.workspace = true
openzeppelin_token.workspace = true
openzeppelin_introspection.workspace = true
alexandria_math.workspace = true
alexandria_encoding.workspace = true
origami_random.workspace = true
game_components_minigame.workspace = true
game_components_token.workspace = true
game_components_metagame.workspace = true
game_components_utils.workspace = true
graffiti.workspace = true

[[target.starknet-contract]]
casm = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    "game_components_token::examples::full_token_contract::FullTokenContract",
    "game_components_token::examples::minigame_registry_contract::MinigameRegistryContract",
]

[dev-dependencies]
dojo_cairo_test.workspace = true
cairo_test.workspace = true
