world_address = "0x01bfa92665fb815c9ec5f37c562a5c9a06fdf23ce022c1d33d4ac07cef5ad80c"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[indexing]
pending = true
transactions = true
namespaces = ["zkube_budo_v1_1_0", "budokan_v_1_0_6"]
contracts = [
  "erc721:0x1e0b80823ba036c8366c2434dad9d5bb35662a7b1d0afbdc69c5f0a7fff3513"
]

[events]
raw = true

[sql]
historical = [
  "zkube_budo_v1_1_0-TrophyProgression",
]