world_address = "0x055e5fe566f984b6fead68ace67278ecdefdc93a48f5509bc61c66f68af6a97f"
rpc = "https://api.cartridge.gg/x/zkube-djizus/katana"

[indexing]
pending = true
transactions = true
namespaces = ["zkube_budo_v1_2_0"]
contracts = [
  "erc721:0x062347854b5817b3c8101014b5813fb0b5db48e4df2a0a9dada8cbdab191b064"
]

[events]
raw = true

[sql]
historical = [
  "zkube_budo_v1_2_0-TrophyProgression",
]
