world_address = "0x5c6d0020a9927edca9ddc984b97305439c0b32a1ec8d3f0eaf6291074cc9799"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[indexing]
pending = true
transactions = true
namespaces = ["zkube_budo_v1_1_0", "budokan_1_0_7"]

[events]
raw = true

[sql]
historical = [
  "zkube_budo_v1_1_0-TrophyProgression",
]