world_address = "0x5c6d0020a9927edca9ddc984b97305439c0b32a1ec8d3f0eaf6291074cc9799"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"

[indexing]
pending = true
transactions = true
namespaces = ["zkube_budo_v1_1_0", "budokan_v_1_0_7"]
contracts = [
  "erc721:0x1e0b80823ba036c8366c2434dad9d5bb35662a7b1d0afbdc69c5f0a7fff3513"
]

[events]
raw = true

[sql]
historical = [
  "zkube_budo_v1_1_0-TrophyProgression",
  "zkube_budo_v1_1_0-StartGame",
  "zkube_budo_v1_1_0-UseBonus"
]