world_address = "0x054b04ebd35f35e18579f2a404c4ca85a89d7b9e85c98bd70e8a28b32ff5b964"
rpc = "https://api.cartridge.gg/x/zkube-djizus/katana"

[indexing]
pending = true
transactions = true
namespaces = ["zkube_budo_v1_2_0"]
contracts = [
  "erc721:0x062347854b5817b3c8101014b5813fb0b5db48e4df2a0a9dada8cbdab191b064",
  "ERC1155:0x7c4cd5ae97baaccccecbead11ac744b38fcbd606e9afd6e4d3be5d48fb54fbc"
]

[events]
raw = true

[sql]
historical = [
  "zkube_budo_v1_2_0-TrophyProgression",
]
